name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: prepare test
      run:  git clone --depth 1 https://github.com/sstephenson/bats.git tests/bats &> /dev/null && chmod -R +x tests/bats

    - name: test
      run: ./ci.sh test

    - name: prepare lint-bash
      run:  cd tests && wget -qO- 'https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz' | tar -xJ && chmod -R +x shellcheck-stable

    - name: lint-bash
      run: ./ci.sh lint-bash
